


spring:
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: coderlavesh@gmail.com
    password: bvjm gdtp aceo ciam
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: dev

#
#api:
#  URI: https://zenquotes.io/api/quotes


